apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-cnoe-controlplane-${{values.clusterName}}
spec:
  accessModes: ['ReadWriteOnce']
  storageClassName: mygp2-delete
  resources:
    requests:
      storage: 10Gi