apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: create-pvc-${{values.clusterName}}-
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  serviceAccountName: pvc-creator-loki-pipline
  templates:
    - name: main
      steps:
        - - name: controlplane
            template: controlplane
        - - name: dataplane
            template: dataplane
        - - name: infrplane
            template: infrplane
    - name: controlplane
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: loki-cnoe-controlplane-${{values.clusterName}}
            namespace: argo
          spec:
            storageClassName: mygp2-delete
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 10Gi
    - name: dataplane
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: loki-cnoe-dataplane-${{values.clusterName}}
            namespace: argo
          spec:
            storageClassName: mygp2-delete
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 10Gi
    - name: infrplane
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: loki-cnoe-infrplane-${{values.clusterName}}
            namespace: argo
          spec:
            storageClassName: mygp2-delete
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 10Gi