apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-cnoe-infrplane-${{values.clusterName}}
  namespace: argo
spec:
  accessModes: ['ReadWriteOnce']
  storageClassName: mygp2-delete
  resources:
    requests:
      storage: 10Gi