apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: reply-platform-intership
  title: Create Reply platform microservice
  description: Create the security perimeter for the platform microservice
spec:
  owner: ro.distefano
  type: job
  parameters:
    - title: Configuration Options
      required:
        - eksVersion
        - awsRegion
        - clusterName
      properties:
        clusterName:
          title: Enter cluster name to create
          type: string
          description: repository name
        eksVersion:
          title: Enter EKS version to use
          type: string
          default: 1.28
          description: EKS version to use
        awsRegion:
          title: Enter AWS region to use
          type: string
          default: eu-west-1
          description: AWS region to use
  steps:
    - id: create-repo
      name: Create Platform applicative repository
      action: github:repo:create
      input:
        repoUrl: github.com?owner=CNOE-ORG-TEST&repo=${{ parameters.clusterName }}&organization=CNOE-ORG-TEST

    - id: fetch-applicative-template
      name: Fetch Applicative Template
      action: fetch:template
      input:
        url: ./applicative-template/
        targetPath: ./applicative-template-compiled/
        values:
          clusterName: ${{ parameters.clusterName }} #Parametro sostituito nel file applicative-template/nginx.yaml
          eksVersion: ${{ parameters.eksVersion }} #Parametro sostituito nel file applicative-template/infrastructure/k8s/catalog-info.yaml
          region: ${{ parameters.awsRegion }} #Parametro sostituito nel template application.yaml

    - id: init-applicative-repo
      name: Initialize Applicative Repository
      action: github:repo:push
      input:
        repoUrl: github.com?owner=CNOE-ORG-TEST&repo=${{ parameters.clusterName }}&organization=CNOE-ORG-TEST
        defaultBranch: main
        sourcePath: ./applicative-template-compiled/
    - id: wait
      name: Waiting for the repo to be ready
      action: "roadiehq:utils:sleep"
      input:
        amount: 5

    - id: register-workflow
      name: Register workflow
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-applicative-repo'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info-workflow.yaml"

    # - id: register-cd
    #   name: Register cd
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['init-applicative-repo'].output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info-cd.yaml"