apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-controlplane
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-controlplane
      emptyDir: { }
  templates:
    - name: main
      steps:
        - - name: pull
            template: pull-step
        - - name: check
            template: check-step
        - - name: deploy
            template: deploy-step
        - - name: postDeploy
            template: postDeploy-step
        - - name: test
            template: test-step

    # definition of the pull step
    - name: pull-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-pull
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.clusterName}}Controlplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the check step
    - name: check-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared


    # definition of the deploy step
    - name: deploy-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /data/shared

    # definition of the post deploy step
    - name: postDeploy-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared

    # definition of the test step
    - name: test-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
