apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-controlplane-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-controlplane
      hostPath:
        path: /mnt/shared-controlplane
        type: DirectoryOrCreate
  templates:
    - name: main
      steps:
        - - name: pull
            template: pull-step
        - - name: check
            template: check-step
        - - name: deploy
            template: deploy-step
        - - name: postDeploy
            template: post-deploy-step
        - - name: test
            template: test-step

    # definition of the pull step
    - name: pull-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-pull
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.clusterName}}Controlplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the check step
    - name: check-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-check
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
        env:
          - name: GITHUB_ORG
            value: "CNOE-ORG-TEST"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN


    # definition of the deploy step
    - name: deploy-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-deploy
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared

    # definition of the post deploy step
    - name: post-deploy-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-post-deploy
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared

    # definition of the test step
    - name: test-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-test
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
