apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-dataplane
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-dataplane
      emptyDir: { }
  templates:
    - name: main
      steps:
        - - name: pull
            template: pull-step
        - - name: check
            template: check-step
        - - name: deploy
            template: deploy-step
        - - name: test
            template: test-step

    # definition of the pull step
    - name: pull-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.eksVersion}}Dataplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the check step
    - name: check-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared

    # definition of the deploy step
    - name: deploy-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared

    # definition of the test step
    - name: test-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'to implement'"]
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared
