apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-infrplane
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-infrplane
      emptyDir: { }
  templates:
    - name: main
      steps:
        - - name: pull
            template: pull-step
        - - name: customization
            template: customization-step
        - - name: deploy
            template: deploy-step
        - - name: test
            template: test-step

    # definition of the pull step
    - name: pull-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'clusterName: $clusterName region: $region eksVersion: $eksVersion'"]
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /data/shared
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.eksVersion}}Infrplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the customization step
    - name: customization-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'clusterName: $clusterName region: $region eksVersion: $eksVersion'"]
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /data/shared

    # definition of the deploy step
    - name: deploy-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'clusterName: $clusterName region: $region eksVersion: $eksVersion'"]
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /data/shared

    # definition of the test step
    - name: test-step
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo 'clusterName: $clusterName region: $region eksVersion: $eksVersion'"]
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /data/shared
