name: Update dataplane of ${{values.clusterName}} cluster

on:
  push:
    paths-ignore:
      - '.github/workflows/onPushWorkflow.yaml'
    branches:
      - main

jobs:
  send_post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send request to webhook
        run: |
          URL="http://trigger-workflow.lab.cna.stormreply.com/trigger"
          DATA='{"clusterName": "${{values.clusterName}}", "planeName": "dataplane"}'
          
          curl -X POST -H "Content-Type: application/json" -d "$DATA" "$URL"

          if [ $? -eq 0 ]; then
            echo "Success"
          else
            echo "Error"
            exit 1
          fi
