apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{values.clusterName}}-monitor-cluster-loki"
  description: Monitor ${{values.clusterName}} cluster created with LOKI
  annotations:
    argo-workflows.cnoe.io/label-selector: "cluster-name=${{values.clusterName}}"
    backstage.io/kubernetes-namespace: "argo"
    argo-workflows.cnoe.io/cluster-name: local
spec:
  type: service
  lifecycle: experimental
  owner: "ro.distefano"