apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-cm-${{values.clusterName}}
  namespace: argo
data:
  variables.json: |
    {
      "clusterName": "${{values.clusterName}}",
      "region": "${{values.region}}",
      "awsAccountId": "${{values.awsAccountId}}",
      "vpcId": "${{values.vpcId}}",
      "feSubnetIds": "${{values.feSubnetIds}}",
      "beSubnetIds": "${{values.beSubnetIds}}",
      "securityGroupIds": "${{values.securityGroupIds}}",
      "env": "${{values.environmentTag}}",
      "keyName": "${{values.keyName}}"
    }
