apiVersion: v1
kind: PersistentVolume
metadata:
  name: controlplane-${{values.clusterName}}-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/shared-controlplane
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controlplane-${{values.clusterName}}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-controlplane-${{values.clusterName}}
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-controlplane
      persistentVolumeClaim:
        claimName: controlplane-${{values.clusterName}}-pvc
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: pull
            template: controlplane-pull-step
        - - name: check
            template: controlplane-check-step
        - - name: deploy
            template: controlplane-deploy-step
        - - name: postDeploy
            template: controlplane-post-deploy-step
        - - name: test
            template: controlplane-test-step

    # definition of the pull step
    - name: controlplane-pull-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-pull
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
          - name: variables-volume
            mountPath: /etc/config
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.clusterName}}Controlplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the check step
    - name: controlplane-check-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-check
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
        env:
          - name: GITHUB_ORG
            value: "CNOE-ORG-TEST"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN


    # definition of the deploy step
    - name: controlplane-deploy-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-deploy
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared

    # definition of the post deploy step
    - name: controlplane-post-deploy-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-post-deploy
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared

    # definition of the test step
    - name: controlplane-test-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/controlplane-test
        volumeMounts:
          - name: shared-volume-controlplane
            mountPath: /shared
