apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-dataplane-${{values.clusterName}}
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: create-pvc
            template: dataplane-create-pvc
        - - name: pull
            template: dataplane-pull-step
        - - name: check
            template: dataplane-check-step
        - - name: deploy
            template: dataplane-deploy-step
        - - name: test
            template: dataplane-test-step
        - - name: delete-pvc
            template: dataplane-delete-pvc

    # definition of the create-vpc step
    - name: dataplane-create-pvc
      resource:
        action: apply
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: loki-cnoe-dataplane-${{values.clusterName}}
            namespace: argo
          spec:
            storageClassName: mygp2-delete
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 10Gi
    # definition of the pull step
    - name: dataplane-pull-step
      volumes:
        - name: shared-volume-dataplane
          persistentVolumeClaim:
            claimName: loki-cnoe-dataplane-${{values.clusterName}}
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/dataplane-pull
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared
          - name: variables-volume
            mountPath: /etc/config
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.clusterName}}Dataplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the check step
    - name: dataplane-check-step
      volumes:
        - name: shared-volume-dataplane
          persistentVolumeClaim:
            claimName: loki-cnoe-dataplane-${{values.clusterName}}
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/dataplane-check
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared
        env:
          - name: GITHUB_ORG
            value: "CNOE-ORG-TEST"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the deploy step
    - name: dataplane-deploy-step
      volumes:
        - name: shared-volume-dataplane
          persistentVolumeClaim:
            claimName: loki-cnoe-dataplane-${{values.clusterName}}
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/dataplane-deploy
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared

    # definition of the test step
    - name: dataplane-test-step
      volumes:
        - name: shared-volume-dataplane
          persistentVolumeClaim:
            claimName: loki-cnoe-dataplane-${{values.clusterName}}
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/dataplane-test
        volumeMounts:
          - name: shared-volume-dataplane
            mountPath: /shared

    # definition of the delete-vpc step
    - name: dataplane-delete-pvc
      resource:
        action: delete
        manifest: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: loki-cnoe-dataplane-${{values.clusterName}}
            namespace: argo
          spec:
            storageClassName: mygp2-delete
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 10Gi
