apiVersion: v1
kind: PersistentVolume
metadata:
  name: infrplane-${{values.clusterName}}-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/shared-controlplane
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infplane-${{values.clusterName}}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-infrplane-${{values.clusterName}}
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: shared-volume-infrplane
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-infrplane
      persistentVolumeClaim:
        claimName: infrplane-${{values.clusterName}}-pvc
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: pull
            template: infrplane-pull-step
        - - name: customization
            template: infrplane-customization-step
        - - name: deploy
            template: infrplane-deploy-step
        - - name: test
            template: infrplane-test-step

    # definition of the pull step
    - name: infrplane-pull-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/infrplane-pull
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /shared
          - name: variables-volume
            mountPath: /etc/config
        env:
          - name: GITHUB_REPO
            value: "CNOE-ORG-TEST/${{values.clusterName}}Infrplane"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the customization step
    - name: infrplane-customization-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/infrplane-customization
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /shared
        env:
          - name: GITHUB_ORG
            value: "CNOE-ORG-TEST"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the deploy step
    - name: infrplane-deploy-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/infrplane-deploy
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /shared
        env:
          - name: GITHUB_ORG
            value: "CNOE-ORG-TEST"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token-cnoeorg-secret
                key: GITHUB_TOKEN

    # definition of the test step
    - name: infrplane-test-step
      container:
        image: 523753954008.dkr.ecr.eu-west-1.amazonaws.com/intership-cnoe-loki/infrplane-test
        volumeMounts:
          - name: shared-volume-infrplane
            mountPath: /shared
