apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loki-build-cluster-
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: shared-volume-controlplane
      spec:
        storageClassName: mygp2
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: shared-volume-dataplane
      spec:
        storageClassName: mygp2
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: shared-volume-infrplane
      spec:
        storageClassName: mygp2
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: controlplane
            templateRef:
              name: build-controlplane-${{values.clusterName}}
              template: main
        - - name: dataplane
            templateRef:
              name: build-dataplane-${{values.clusterName}}
              template: main
        - - name: infrplane
            templateRef:
              name: build-infrplane-${{values.clusterName}}
              template: main