apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loki-build-cluster-
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
    - name: shared-volume-controlplane
      persistentVolumeClaim:
        claimName: loki-cnoe-controlplane-${{values.clusterName}}
    - name: shared-volume-dataplane
      persistentVolumeClaim:
        claimName: loki-cnoe-dataplane-${{values.clusterName}}
    - name: shared-volume-infrplane
      persistentVolumeClaim:
        claimName: loki-cnoe-infrplane-${{values.clusterName}}
  templates:
    - name: main
      steps:
        - - name: controlplane
            templateRef:
              name: build-controlplane-${{values.clusterName}}
              template: main
        - - name: dataplane
            templateRef:
              name: build-dataplane-${{values.clusterName}}
              template: main
        - - name: infrplane
            templateRef:
              name: build-infrplane-${{values.clusterName}}
              template: main