apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loki-build-cluster-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: shared-volume-controlplane
      hostPath:
        path: /mnt/shared-controlplane
        type: DirectoryOrCreate
    - name: shared-volume-dataplane
      hostPath:
        path: /mnt/shared-dataplane
        type: DirectoryOrCreate
    - name: shared-volume-infrplane
      hostPath:
        path: /mnt/shared-infrplane
        type: DirectoryOrCreate
    - name: variables-volume
      configMap:
        name: variables-${{values.clusterName}}-cm
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: controlplane
            templateRef:
              name: build-controlplane-${{values.clusterName}}
              template: main
        - - name: dataplane
            templateRef:
              name: build-dataplane-${{values.clusterName}}
              template: main
        - - name: infrplane
            templateRef:
              name: build-infrplane-${{values.clusterName}}
              template: main