apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: loki-build-cluster-${{values.clusterName}}
  namespace: argo
  labels:
    project-id: loki
    cluster-name: ${{values.clusterName}}
spec:
  podGC:
    strategy: OnPodSuccess
    deleteDelayDuration: 30s
  entrypoint: main
  serviceAccountName: argo-workflows-loki-sa
  volumes:
    - name: variables-volume
      configMap:
        name: variables-cm-${{values.clusterName}}
        items:
          - key: variables.json
            path: variables.json
  templates:
    - name: main
      steps:
        - - name: controlplane
            templateRef:
              name: build-controlplane-${{values.clusterName}}
              template: main
        - - name: dataplane
            templateRef:
              name: build-dataplane-${{values.clusterName}}
              template: main
        - - name: infrplane
            templateRef:
              name: build-infrplane-${{values.clusterName}}
              template: main